### ISSUE TITLE
cputhrottle parameter from INI file nto working

### ISSUE THREAD

**Issue by Pitou1** [tursilion/classic99#2]
Hello,

I'm trying to set the cputhrottle parameter to 2 (System Maximum) in the classic99.ini file, but when I start the emulator, it always revert back to 1 (Normal). I'm using Windows 10.

Any idea?

Thank you.

Pitou!

**Comment by tursilion** [comment]
Ah, the throttle system is pretty mangled from decades of development. I don't think it's persistent anymore. Do you need it to /start/ in system maximum? Most people find that mode unstable.

**Comment by Pitou1** [comment]
Yes I'm trying to start the emu in system max mode. It's not that important, but since I'm testing a lot of wav file, it's more convenient.

However in the meantime I found a small workaround. I start the emu, then set the system max from the menu, then load a wav file. Then, I just reset the emu with ctrl+alt and +. This way it keeps the speed at max.

Pitou!

**Comment by tursilion** [comment]
This should be fixed now, I reworked this setting with an eye to letting it start up in whatever mode back in 399.043, so I'm going to close this issue.

**Comment by Pitou1** [comment]
Thanks very much Mike for this. I'm gonna test for sure!
