### ISSUE TITLE
Just want to say thanks

### ISSUE THREAD

**Issue by d3x0r** [tursilion/classic99#5]
Seems to work well :)  My first computer - ahh the memories...

Before running across this was just looking for the font - could have sworn this had 0-31 and 128+ characters too like the tandy 1000; but that was a long time ago, but I found these manuals

http://dunfield.classiccmp.org/ti/usrguide.pdf - full manual that came with the system... (how to write basic)
http://dunfield.classiccmp.org/ti/beginbas.pdf 
http://dunfield.classiccmp.org/ti/basicref.pdf

**Comment by tursilion** [comment]
hehe, thanks. And yeah, that's right - only characters 32-126 are defined on the TI (and lowercase letters are actually small capitals! ;) )
