### ISSUE TITLE
TE 2 speech broken

### ISSUE THREAD

**Issue by blindphoneman** [tursilion/classic99#7]
Hi:

Something has changed, so that, when I try to use speech with TE2, the system tries to speak, then locks up.

This was working in a previous version from December 2019, but, haven't downloaded it until now, so not sure where the change happened.

Thanks!

**Comment by tursilion** [comment]
TE2 speech has never been supported due to the synth emulator being unable to properly halt the CPU... if it worked, you were lucky.

Sorry, but I won't be looking into this anytime soon.

**Comment by tursilion** [comment]
Did it really work back in December 2019? What application were you using?

(Damn it, now I'm thinking about it... ;) )

**Comment by tursilion** [comment]
To my surprise, it actually sort of works for me... I typed this at the command prompt and it was fine:

OPEN #1:"SPEECH",OUTPUT
PRINT #1:"HELLO WORLD"

except for sounding terrible, but that's due to wrong emulation. Can you send me the app which is locking up?

**Comment by tursilion** [comment]
(Longer strings garble, but that's actually the behaviour I was expecting...)

**Comment by blindphoneman** [comment]
Hi: This was version 399.015.  If I didn’t get the version number right, it was dated 12/26/99. All I did was load up a basic program in TE2 and do a LIST “SPEECH”.  Yes, it sounded off, but, it read the lines. Now, in the latest version, it does what you noticed, long strings garble, and it locks up. Wish I would have downloaded newer ones between then and now.  That way, I could tell you where the change happened. No big deal.  I knew it wasn’t high priority, and, I can use MAME for TTS in a pinch. You might be surprised, but, I find classic99 is one of the best tools I’ve come across to do work on basic programs, since I can list to clip and re-enter from clip.  As A blind user, I can edit with Windows or DOS tools easier than I can on any TI system, emulated or real—That’s off-topic , so I will limit it to this. Thanks!

**Comment by tursilion** [comment]
Well, I'm surprised it used to work, but that does suggest it might yet be fixable without needing to finish 4.0, which is really, really lagging behind. A LIST is an easy test, so I'll try to spend some time on it next weekend.

**Comment by blindphoneman** [comment]
No problem.  Thanks for looking into it.

**Comment by tursilion** [comment]
I sat down tonight and this is all fixed now.. for the first time I'm willing to say Classic99's speech works... at least until it breaks. ;)

I have imported the latest MAME core, so the correct speech chip is in place. I have worked around the audio buffering so it's no longer jittery and froggy sounding. And most importantly, I found the bug that you found that I didn't even know ever worked - I broke the way CPU hold worked in 399.037

So, hopefully this version will work for you, and I'm also hopeful it will be a little more pleasant to listen to! I'll leave this issue open for a few days and then close it once we know.

**Comment by blindphoneman** [comment]
Hi Mike: You just blew me away… I’m speechless, but, Classic 99 is not.  I’ve got it singing caroline right now as I type.  It sounds great!  Gonna run a long BASIC listing through it, but, I am 99.99 per cent sure of the result already. Speech with built-in vocabulary sounds good also and Alpiner and Parsec are speaking great also.  Maybe a couple odd timing issues, but that’s very minor compared to what you’ve just accomplished. I never expected this, and certainly not this quick. Again, this sounds fantastic! This was a nice surprise.

**Comment by blindphoneman** [comment]
Hi Mike: You may also be interested to know that Classic 99 now runs ernie&bert.  Give it a shot. Thanks!

**Comment by tursilion** [comment]
Thanks! Glad it worked for you! I will close this now. :)
